In [ ]:
import pandas as pd

df = pd.read_excel("/content/Data_set_populated.xlsx")

df.shape
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   file_name                         100 non-null    object
 1   decision                          100 non-null    object
 2   duration_s                        100 non-null    float64
 3   width                             100 non-null    int64
 4   height                            100 non-null    int64
 5   fps                               100 non-null    float64
 6   mean_frame_diff                   100 non-null    float64
 7   max_frame_diff                    100 non-null    float64
 8   p90_frame_diff                    100 non-null    float64
 9   std_frame_diff                    100 non-null    float64
 10  scene_cuts                        100 non-null    int64
 11  max_hist_diff                     100 non-null    float64
 12  sampled_frames                    100 non-null    int64
 13  manual_scene_cuts                 100 non-null    int64
 14  cuts_match                        100 non-null    object
 15  description                       100 non-null    object
 16  personal description/observation  100 non-null    object
dtypes: float64(7), int64(5), object(5)
memory usage: 13.4+ KB

In [ ]:
print(df.isna().sum())
print("\n")
print(df.duplicated().sum())
print("\n")
print(df.nunique())

file_name                           0
decision                            0
duration_s                          0
width                               0
height                              0
fps                                 0
mean_frame_diff                     0
max_frame_diff                      0
p90_frame_diff                      0
std_frame_diff                      0
scene_cuts                          0
max_hist_diff                       0
sampled_frames                      0
manual_scene_cuts                   0
cuts_match                          0
description                         0
personal description/observation    0
dtype: int64


0


file_name                           100
decision                              2
duration_s                           61
width                                14
height                               15
fps                                   7
mean_frame_diff                      90
max_frame_diff                       93
p90_frame_diff                       94
std_frame_diff                       87
scene_cuts                            5
max_hist_diff                        95
sampled_frames                       41
manual_scene_cuts                     6
cuts_match                            2
description                          93
personal description/observation     44
dtype: int64

In [ ]:
features = [
    "mean_frame_diff",
    "max_frame_diff",
    "p90_frame_diff",
    "std_frame_diff",
    "scene_cuts",
    "max_hist_diff"
]

df[features].describe().T

,count,mean,std,min,25%,50%,75%,max
mean_frame_diff,100.0,0.052550,0.035978,0.0036,0.022325,0.05095,0.073150,0.1504
max_frame_diff,100.0,0.127224,0.092183,0.0090,0.053200,0.10425,0.191700,0.4958
p90_frame_diff,100.0,0.084139,0.060117,0.0062,0.033925,0.07400,0.117225,0.2369
std_frame_diff,100.0,0.026184,0.020985,0.0005,0.008275,0.01875,0.037250,0.0749
scene_cuts,100.0,0.390000,0.815197,0.0000,0.000000,0.00000,0.250000,4.0000
max_hist_diff,100.0,0.284670,0.365174,0.0000,0.012175,0.05910,0.528225,1.3889

In [ ]:
df[features].corr().round(2)

,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,scene_cuts,max_hist_diff
mean_frame_diff,1.00,0.67,0.88,0.59,0.39,0.35
max_frame_diff,0.67,1.00,0.76,0.91,0.58,0.72
p90_frame_diff,0.88,0.76,1.00,0.83,0.40,0.43
std_frame_diff,0.59,0.91,0.83,1.00,0.49,0.62
scene_cuts,0.39,0.58,0.40,0.49,1.00,0.62
max_hist_diff,0.35,0.72,0.43,0.62,0.62,1.00

In [ ]:
df["cuts_match"].value_counts()

cuts_match
Yes    71
No     29
Name: count, dtype: int64

In [ ]:
df[df["cuts_match"] == "No"][
    ["file_name", "scene_cuts", "manual_scene_cuts", "description"]
]

,file_name,scene_cuts,manual_scene_cuts,description
4,1774855609672222 (1).mp4,1,2,Boy watches an old TV that switches from carto...
5,1774855609672222.mp4,1,2,Boy watches an old TV that switches from carto...
6,1774909312798671.mp4,0,2,Angry green troll character shoots fire in a b...
10,226c6fa3-3f23-4077-97b6-25163b21e0a4_0.mp4,0,1,Static juice-press ad screen; liquid level ani...
18,5221b8f5-8de1-4aef-8b13-d73352a40930_0.mp4,0,2,A metal ball drops and crushes a tiered cake i...
31,Block Blas-360 X 640-2026-07-01-61f4ff2f7cc3d7...,0,1,Animated girl plays a block puzzle game in a c...
33,Block Blast (2).mp4,0,2,A pencil draws lines connecting matching color...
37,Brilliant Sort™ Diamond Puzzle-1080 X 1920-202...,0,1,A red heart-shaped gift box opens to reveal a ...
41,Coloring Games-1080 X 1920-2026-07-15-7af7eaa0...,0,1,Camera zooms in on a candy-stamping machine in...
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,3,5,"Montage: a burning castle city, a dark cloud t..."
47,Gardenscapes-720 X 1280-2026-06-29-784808c0fc1...,1,2,"Bride holds a bouquet in a dressing room, then..."
48,Gardenscapes-720 X 720-2026-06-29-d67a2736fefd...,0,1,Camera pans across a cactus garden path with f...
50,Jewel 8.mp4,0,1,Woman with curly hair reacts and talks to came...
53,Ludo King-512 X 640-2026-06-04-e0e58800a975d18...,1,0,Fiery corridor and smoke effects coalesce into...
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,1,4,"Race cars speed around a track, then the view ..."
55,Ludo STAR-640 X 360-2026-05-22-b2cc781bea95f29...,1,0,Sprinters crouch at starting blocks on a track...
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,1,0,"Colored marbles race down a glowing track, the..."
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,1,0,"Colored marbles race down a glowing track, the..."
61,Match Factory!-224 X 400-2026-01-08-aab035c317...,0,1,A rabbit-costumed character sits at a counter ...
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,4,0,TikTok-style ad rapidly cuts between a woman h...
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,4,0,TikTok-style ad rapidly cuts between a woman h...
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,1,3,"Man and woman talk on a street, with a phone c..."
73,Solitaire Smash_ Real Cash!-720 X 1280-2026-06...,0,2,Man on a couch and a pregnant woman talk about...
74,Solitaire Smash_ Real Cash-720 X 1280-2026-06-...,1,4,"Couple converse in a living room ('hey honey, ..."
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,1,3,Bottles labeled 'no ads/no wifi' on a balcony ...
77,teenpatti29.mp4,1,2,Man talks to camera with a 'WINNER' banner ove...
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,0,4,"Two men fish by a river; one runs off, then a ..."
84,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,2,0,Close underwater texture shot transitions to a...
92,Untitled design (19).mp4,0,1,Two food-mascot characters argue in a fridge/k...

In [ ]:
df.groupby(
    pd.cut(
        df["duration_s"],
        bins=[0, 5, 7, float("inf")],
        labels=["<=5s", "5-7s", ">7s"]
    )
)["decision"].value_counts()

/tmp/ipykernel_1263/1060283442.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

duration_s  decision
<=5s        ELIGIBLE    54
            EXCLUDE      5
5-7s        ELIGIBLE    18
            EXCLUDE      1
>7s         EXCLUDE     22
            ELIGIBLE     0
Name: count, dtype: int64

In [ ]:
#extreme clips

df.nlargest(10, "mean_frame_diff")[
    ["file_name", "duration_s", "mean_frame_diff", "scene_cuts", "description"]
]

,file_name,duration_s,mean_frame_diff,scene_cuts,description
32,Block Blast (1).mp4,6.20,0.1504,0,Static aerial view of a busy city street (Time...
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,0.1431,0,Skydiver free-falls through clouds and opens a...
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,1,"Colored marbles race down a glowing track, the..."
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,1,"Colored marbles race down a glowing track, the..."
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.1303,1,"Race cars speed around a track, then the view ..."
36,Block Blast.mp4,4.20,0.1174,1,"Two cats hug inside a cage in a dark alley, th..."
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,4,TikTok-style ad rapidly cuts between a woman h...
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,4,TikTok-style ad rapidly cuts between a woman h...
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.1126,1,Bottles labeled 'no ads/no wifi' on a balcony ...
9,1e8c1cb1-eff0-45b0-b923-d6651209e08f_0.mp4,4.03,0.1047,0,Girl drives a red tractor; camera pulls back t...

In [ ]:
df.nlargest(10, "mean_frame_diff")[
    [
        "file_name",
        "duration_s",
        "mean_frame_diff",
        "max_frame_diff",
        "p90_frame_diff",
        "std_frame_diff",
        "scene_cuts",
        "manual_scene_cuts",
        "cuts_match",
        "description",
        "personal description/observation"
    ]
]

,file_name,duration_s,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,scene_cuts,manual_scene_cuts,cuts_match,description,personal description/observation
32,Block Blast (1).mp4,6.20,0.1504,0.2792,0.2369,0.0651,0,0,Yes,Static aerial view of a busy city street (Time...,guy comparing his hand size
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,0.1431,0.1782,0.1671,0.0204,0,0,Yes,Skydiver free-falls through clouds and opens a...,correct
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.2217,0.1983,0.0460,1,0,No,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.2217,0.1983,0.0460,1,0,No,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.1303,0.2624,0.2082,0.0503,1,4,No,"Race cars speed around a track, then the view ...",total 4 cuts observed
36,Block Blast.mp4,4.20,0.1174,0.2021,0.1516,0.0368,1,1,Yes,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.2295,0.1818,0.0518,4,0,No,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.2295,0.1818,0.0518,4,0,No,TikTok-style ad rapidly cuts between a woman h...,no scene cut
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.1126,0.2224,0.1320,0.0307,1,3,No,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
9,1e8c1cb1-eff0-45b0-b923-d6651209e08f_0.mp4,4.03,0.1047,0.1310,0.1271,0.0279,0,0,Yes,Girl drives a red tractor; camera pulls back t...,correct

In [ ]:
df.nlargest(10, "max_hist_diff")[[
    "file_name",
    "duration_s",
    "max_hist_diff",
    "scene_cuts",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]]

,file_name,duration_s,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,1.3889,3,5,"Montage: a burning castle city, a dark cloud t...",correct
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,1.2282,2,2,"A mountain rock spelling 'ADS' crumbles, then ...",correct
4,1774855609672222 (1).mp4,6.27,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
5,1774855609672222.mp4,6.27,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,1.1788,2,2,"A boat capsizes in ocean waves, then cuts to a...",correct
77,teenpatti29.mp4,2.94,1.0292,1,2,Man talks to camera with a 'WINNER' banner ove...,2 cuts
97,Word Search Zen-Word Find-720 X 1280-2026-01-2...,3.70,0.9971,0,0,A styrofoam block is carved/crushed in one con...,correct
3,1774855008922425.mp4,3.80,0.9726,2,2,"Wooden box unfolds into a flat Ludo board, whi...",correct
55,Ludo STAR-640 X 360-2026-05-22-b2cc781bea95f29...,4.50,0.8991,1,0,Sprinters crouch at starting blocks on a track...,"not cut manually detected, the on screen text ..."
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...

In [ ]:
df.nlargest(10, "max_hist_diff")[[
    "file_name",
    "duration_s",
    "max_hist_diff",
    "scene_cuts",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]]

,file_name,duration_s,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,1.3889,3,5,"Montage: a burning castle city, a dark cloud t...",correct
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,1.2282,2,2,"A mountain rock spelling 'ADS' crumbles, then ...",correct
4,1774855609672222 (1).mp4,6.27,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
5,1774855609672222.mp4,6.27,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,1.1788,2,2,"A boat capsizes in ocean waves, then cuts to a...",correct
77,teenpatti29.mp4,2.94,1.0292,1,2,Man talks to camera with a 'WINNER' banner ove...,2 cuts
97,Word Search Zen-Word Find-720 X 1280-2026-01-2...,3.70,0.9971,0,0,A styrofoam block is carved/crushed in one con...,correct
3,1774855008922425.mp4,3.80,0.9726,2,2,"Wooden box unfolds into a flat Ludo board, whi...",correct
55,Ludo STAR-640 X 360-2026-05-22-b2cc781bea95f29...,4.50,0.8991,1,0,Sprinters crouch at starting blocks on a track...,"not cut manually detected, the on screen text ..."
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...

In [ ]:
df.nlargest(10, "scene_cuts")[
    [
        "file_name",
        "duration_s",
        "scene_cuts",
        "manual_scene_cuts",
        "cuts_match",
        "description",
        "personal description/observation"
    ]
]

,file_name,duration_s,scene_cuts,manual_scene_cuts,cuts_match,description,personal description/observation
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,4,0,No,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,4,0,No,TikTok-style ad rapidly cuts between a woman h...,no scene cut
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,3,5,No,"Montage: a burning castle city, a dark cloud t...",correct
3,1774855008922425.mp4,3.80,2,2,Yes,"Wooden box unfolds into a flat Ludo board, whi...",correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,2,2,Yes,"A boat capsizes in ocean waves, then cuts to a...",correct
44,d27eaec0-1658-4dc0-8d1a-8af605737e32_0.mp4,8.03,2,2,Yes,"Hands light matches, then cuts to a snowy outd...",correct
51,jYn03l7-G46sBmDOIWUDA_output.mp4,5.04,2,2,Yes,Interview cuts between a woman and a man talki...,correct
84,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,8.80,2,0,No,Close underwater texture shot transitions to a...,"no cuts, one continuous shot camera moving up ..."
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,2,2,Yes,"A mountain rock spelling 'ADS' crumbles, then ...",correct
4,1774855609672222 (1).mp4,6.27,1,2,No,Boy watches an old TV that switches from carto...,correct

In [ ]:
df[df["cuts_match"] == "No"][
    [
        "file_name",
        "duration_s",
        "scene_cuts",
        "manual_scene_cuts",
        "cuts_match",
        "mean_frame_diff",
        "max_frame_diff",
        "p90_frame_diff",
        "std_frame_diff",
        "max_hist_diff",
        "description",
        "personal description/observation"
    ]
].sort_values("scene_cuts", ascending=False)

,file_name,duration_s,scene_cuts,manual_scene_cuts,cuts_match,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,max_hist_diff,description,personal description/observation
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,4,0,No,0.1138,0.2295,0.1818,0.0518,0.5787,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,4,0,No,0.1138,0.2295,0.1818,0.0518,0.5787,TikTok-style ad rapidly cuts between a woman h...,no scene cut
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,3,5,No,0.1022,0.3607,0.1973,0.0622,1.3889,"Montage: a burning castle city, a dark cloud t...",correct
84,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,8.80,2,0,No,0.0527,0.1822,0.0755,0.0245,0.4041,Close underwater texture shot transitions to a...,"no cuts, one continuous shot camera moving up ..."
5,1774855609672222.mp4,6.27,1,2,No,0.0207,0.2291,0.0200,0.0351,1.2000,Boy watches an old TV that switches from carto...,correct
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,1,4,No,0.1303,0.2624,0.2082,0.0503,0.6913,"Race cars speed around a track, then the view ...",total 4 cuts observed
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,1,0,No,0.1421,0.2217,0.1983,0.0460,0.8413,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
55,Ludo STAR-640 X 360-2026-05-22-b2cc781bea95f29...,4.50,1,0,No,0.0252,0.1328,0.0575,0.0299,0.8991,Sprinters crouch at starting blocks on a track...,"not cut manually detected, the on screen text ..."
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,1,0,No,0.1421,0.2217,0.1983,0.0460,0.8413,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
53,Ludo King-512 X 640-2026-06-04-e0e58800a975d18...,7.50,1,0,No,0.0980,0.1933,0.1698,0.0456,0.4085,Fiery corridor and smoke effects coalesce into...,corect
4,1774855609672222 (1).mp4,6.27,1,2,No,0.0207,0.2291,0.0200,0.0351,1.2000,Boy watches an old TV that switches from carto...,correct
47,Gardenscapes-720 X 1280-2026-06-29-784808c0fc1...,6.00,1,2,No,0.0391,0.1869,0.0803,0.0422,0.1706,"Bride holds a bouquet in a dressing room, then...","a girl handing over bouquet to bride, cuts onl..."
77,teenpatti29.mp4,2.94,1,2,No,0.0853,0.2576,0.2210,0.0749,1.0292,Man talks to camera with a 'WINNER' banner ove...,2 cuts
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,1,3,No,0.1126,0.2224,0.1320,0.0307,0.6598,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,1,3,No,0.0642,0.3086,0.1429,0.0710,0.5497,"Man and woman talk on a street, with a phone c...",total 3 cuts observed
74,Solitaire Smash_ Real Cash-720 X 1280-2026-06-...,5.00,1,4,No,0.0637,0.2336,0.1907,0.0679,0.7540,"Couple converse in a living room ('hey honey, ...",4 cuts
50,Jewel 8.mp4,3.12,0,1,No,0.0504,0.0800,0.0725,0.0149,0.0264,Woman with curly hair reacts and talks to came...,single cut
33,Block Blast (2).mp4,7.10,0,2,No,0.0269,0.0865,0.0589,0.0223,0.0094,A pencil draws lines connecting matching color...,"correct, excluded possibly due to inconsistent..."
31,Block Blas-360 X 640-2026-07-01-61f4ff2f7cc3d7...,4.70,0,1,No,0.0338,0.0393,0.0381,0.0042,0.0048,Animated girl plays a block puzzle game in a c...,correct
10,226c6fa3-3f23-4077-97b6-25163b21e0a4_0.mp4,3.03,0,1,No,0.0233,0.1593,0.0268,0.0343,0.5759,Static juice-press ad screen; liquid level ani...,"there is a scene change, the blowing effect is..."
18,5221b8f5-8de1-4aef-8b13-d73352a40930_0.mp4,4.20,0,2,No,0.0565,0.1917,0.1710,0.0721,0.2636,A metal ball drops and crushes a tiered cake i...,"single scene cut, first smaller ball drops not..."
6,1774909312798671.mp4,3.70,0,2,No,0.0699,0.1031,0.0933,0.0187,0.1951,Angry green troll character shoots fire in a b...,"Detected anomalies in the frame, initally char..."
48,Gardenscapes-720 X 720-2026-06-29-d67a2736fefd...,3.00,0,1,No,0.0689,0.0991,0.0851,0.0145,0.0129,Camera pans across a cactus garden path with f...,single cut
37,Brilliant Sort™ Diamond Puzzle-1080 X 1920-202...,2.46,0,1,No,0.0693,0.1541,0.1381,0.0435,0.0123,A red heart-shaped gift box opens to reveal a ...,shot changing at the end
41,Coloring Games-1080 X 1920-2026-07-15-7af7eaa0...,3.00,0,1,No,0.0619,0.2694,0.1685,0.0718,0.2794,Camera zooms in on a candy-stamping machine in...,one cut in between two shots
61,Match Factory!-224 X 400-2026-01-08-aab035c317...,3.00,0,1,No,0.0515,0.1095,0.0837,0.0251,0.4547,A rabbit-costumed character sits at a counter ...,single cut to a more closer frame
73,Solitaire Smash_ Real Cash!-720 X 1280-2026-06...,3.80,0,2,No,0.0764,0.2908,0.2086,0.0710,0.7145,Man on a couch and a pregnant woman talk about...,"2 cuts, 3 frames"
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,6.32,0,4,No,0.0627,0.2373,0.1392,0.0568,0.2798,"Two men fish by a river; one runs off, then a ...","4 cuts, wrong observation by LLM"
92,Untitled design (19).mp4,9.60,0,1,No,0.0408,0.1566,0.0985,0.0369,0.5227,Two food-mascot characters argue in a fridge/k...,one cut between

In [ ]:
features = [
    "mean_frame_diff",
    "max_frame_diff",
    "p90_frame_diff",
    "std_frame_diff",
    "max_hist_diff"
]

df[features].describe().T

,count,mean,std,min,25%,50%,75%,max
mean_frame_diff,100.0,0.052550,0.035978,0.0036,0.022325,0.05095,0.073150,0.1504
max_frame_diff,100.0,0.127224,0.092183,0.0090,0.053200,0.10425,0.191700,0.4958
p90_frame_diff,100.0,0.084139,0.060117,0.0062,0.033925,0.07400,0.117225,0.2369
std_frame_diff,100.0,0.026184,0.020985,0.0005,0.008275,0.01875,0.037250,0.0749
max_hist_diff,100.0,0.284670,0.365174,0.0000,0.012175,0.05910,0.528225,1.3889

In [ ]:
df.nlargest(10, "mean_frame_diff")[
    ["file_name", "duration_s", "mean_frame_diff",
     "p90_frame_diff", "max_frame_diff",
     "std_frame_diff", "max_hist_diff",
     "description", "personal description/observation"]
]

,file_name,duration_s,mean_frame_diff,p90_frame_diff,max_frame_diff,std_frame_diff,max_hist_diff,description,personal description/observation
32,Block Blast (1).mp4,6.20,0.1504,0.2369,0.2792,0.0651,0.0686,Static aerial view of a busy city street (Time...,guy comparing his hand size
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,0.1431,0.1671,0.1782,0.0204,0.3680,Skydiver free-falls through clouds and opens a...,correct
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.1983,0.2217,0.0460,0.8413,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.1983,0.2217,0.0460,0.8413,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.1303,0.2082,0.2624,0.0503,0.6913,"Race cars speed around a track, then the view ...",total 4 cuts observed
36,Block Blast.mp4,4.20,0.1174,0.1516,0.2021,0.0368,0.3442,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.1818,0.2295,0.0518,0.5787,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.1818,0.2295,0.0518,0.5787,TikTok-style ad rapidly cuts between a woman h...,no scene cut
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.1126,0.1320,0.2224,0.0307,0.6598,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
9,1e8c1cb1-eff0-45b0-b923-d6651209e08f_0.mp4,4.03,0.1047,0.1271,0.1310,0.0279,0.1905,Girl drives a red tractor; camera pulls back t...,correct

In [ ]:
df.nlargest(10, "max_frame_diff")[
    ["file_name", "duration_s", "mean_frame_diff",
     "max_frame_diff", "p90_frame_diff",
     "std_frame_diff", "max_hist_diff",
     "description", "personal description/observation"]
]

,file_name,duration_s,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,max_hist_diff,description,personal description/observation
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,0.0807,0.4958,0.0879,0.0662,1.1788,"A boat capsizes in ocean waves, then cuts to a...",correct
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,0.1022,0.3607,0.1973,0.0622,1.3889,"Montage: a burning castle city, a dark cloud t...",correct
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,0.0642,0.3086,0.1429,0.0710,0.5497,"Man and woman talk on a street, with a phone c...",total 3 cuts observed
73,Solitaire Smash_ Real Cash!-720 X 1280-2026-06...,3.80,0.0764,0.2908,0.2086,0.0710,0.7145,Man on a couch and a pregnant woman talk about...,"2 cuts, 3 frames"
51,jYn03l7-G46sBmDOIWUDA_output.mp4,5.04,0.0544,0.2891,0.0857,0.0652,0.4226,Interview cuts between a woman and a man talki...,correct
32,Block Blast (1).mp4,6.20,0.1504,0.2792,0.2369,0.0651,0.0686,Static aerial view of a busy city street (Time...,guy comparing his hand size
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,0.0604,0.2729,0.1064,0.0509,1.2282,"A mountain rock spelling 'ADS' crumbles, then ...",correct
41,Coloring Games-1080 X 1920-2026-07-15-7af7eaa0...,3.00,0.0619,0.2694,0.1685,0.0718,0.2794,Camera zooms in on a candy-stamping machine in...,one cut in between two shots
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.1303,0.2624,0.2082,0.0503,0.6913,"Race cars speed around a track, then the view ...",total 4 cuts observed
77,teenpatti29.mp4,2.94,0.0853,0.2576,0.2210,0.0749,1.0292,Man talks to camera with a 'WINNER' banner ove...,2 cuts

In [ ]:
df.nlargest(10, "max_hist_diff")[
    ["file_name", "duration_s", "mean_frame_diff",
     "max_frame_diff", "p90_frame_diff",
     "std_frame_diff", "max_hist_diff",
     "description", "personal description/observation"]
]

,file_name,duration_s,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,max_hist_diff,description,personal description/observation
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,0.1022,0.3607,0.1973,0.0622,1.3889,"Montage: a burning castle city, a dark cloud t...",correct
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,0.0604,0.2729,0.1064,0.0509,1.2282,"A mountain rock spelling 'ADS' crumbles, then ...",correct
4,1774855609672222 (1).mp4,6.27,0.0207,0.2291,0.0200,0.0351,1.2000,Boy watches an old TV that switches from carto...,correct
5,1774855609672222.mp4,6.27,0.0207,0.2291,0.0200,0.0351,1.2000,Boy watches an old TV that switches from carto...,correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,0.0807,0.4958,0.0879,0.0662,1.1788,"A boat capsizes in ocean waves, then cuts to a...",correct
77,teenpatti29.mp4,2.94,0.0853,0.2576,0.2210,0.0749,1.0292,Man talks to camera with a 'WINNER' banner ove...,2 cuts
97,Word Search Zen-Word Find-720 X 1280-2026-01-2...,3.70,0.0661,0.1917,0.0812,0.0321,0.9971,A styrofoam block is carved/crushed in one con...,correct
3,1774855008922425.mp4,3.80,0.0725,0.1090,0.1015,0.0249,0.9726,"Wooden box unfolds into a flat Ludo board, whi...",correct
55,Ludo STAR-640 X 360-2026-05-22-b2cc781bea95f29...,4.50,0.0252,0.1328,0.0575,0.0299,0.8991,Sprinters crouch at starting blocks on a track...,"not cut manually detected, the on screen text ..."
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.2217,0.1983,0.0460,0.8413,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...

In [ ]:
pd.crosstab(
    df["scene_cuts"],
    pd.cut(
        df["max_hist_diff"],
        bins=4,
        labels=["Low", "Medium", "High", "Very High"]
    )
)

max_hist_diff  Low  Medium  High  Very High
scene_cuts
0               64       8     3          0
1                3       5     6          2
2                0       3     1          2
3                0       0     0          1
4                0       2     0          0

In [ ]:
pd.crosstab(
    df["manual_scene_cuts"],
    pd.cut(
        df["max_hist_diff"],
        bins=4,
        labels=["Low", "Medium", "High", "Very High"]
    )
)

max_hist_diff      Low  Medium  High  Very High
manual_scene_cuts
0                   55       9     5          0
1                    7       4     1          0
2                    4       2     3          4
3                    0       2     0          0
4                    1       1     1          0
5                    0       0     0          1

PHASE 2

In [ ]:
candidate_features = [
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff"
]

df[candidate_features].corr().round(2)

                 mean_frame_diff  max_frame_diff  max_hist_diff
mean_frame_diff             1.00            0.67           0.35
max_frame_diff              0.67            1.00           0.72
max_hist_diff               0.35            0.72           1.00

In [ ]:
df[candidate_features].describe().T

,count,mean,std,min,25%,50%,75%,max
mean_frame_diff,100.0,0.052550,0.035978,0.0036,0.022325,0.05095,0.073150,0.1504
max_frame_diff,100.0,0.127224,0.092183,0.0090,0.053200,0.10425,0.191700,0.4958
max_hist_diff,100.0,0.284670,0.365174,0.0000,0.012175,0.05910,0.528225,1.3889

In [ ]:
df["max_frame_minus_hist"] = (
    df["max_frame_diff"].rank(pct=True)
    - df["max_hist_diff"].rank(pct=True)
)

cols = [
    "file_name",
    "duration_s",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "scene_cuts",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]

result = df.loc[
    df["max_frame_minus_hist"].abs().nlargest(10).index,
    cols + ["max_frame_minus_hist"]
].sort_values("max_frame_minus_hist")

result

,file_name,duration_s,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation,max_frame_minus_hist
82,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,11.80,0.0154,0.0323,0.6391,0,0,Static illustrated senior portrait with a moun...,correct,-0.690
95,Vita Solitaire for Seniors-360 X 640-2026-07-0...,12.30,0.0060,0.0573,0.5448,0,0,Static satellite/space station illustration wi...,correct,-0.470
22,81dca706-0e11-4d4d-8f00-deee6a3decc7_0.mp4,12.52,0.0053,0.0484,0.3211,0,0,Static word-game ad card over rolling hills; c...,correct,-0.430
3,1774855008922425.mp4,3.80,0.0725,0.1090,0.9726,2,2,"Wooden box unfolds into a flat Ludo board, whi...",correct,-0.400
34,Block Blast-1.mp4,4.50,0.0197,0.0284,0.0476,0,0,Static aerial view of a busy city street with ...,An hour glass rotating it is filled with color...,-0.395
67,Solitaire Associations Journey-360 X 640-2026-...,4.00,0.0153,0.0259,0.0284,0,0,Static kitten-pattern background with promotio...,correct,-0.350
91,Township-720 X 720-2026-07-03-293ca71cc156f3c4...,10.60,0.0162,0.0304,0.0386,0,0,Farm woman walks past a barn and sheep while d...,fram woman trying to push haystack into the barn,-0.350
37,Brilliant Sort™ Diamond Puzzle-1080 X 1920-202...,2.46,0.0693,0.1541,0.0123,0,1,A red heart-shaped gift box opens to reveal a ...,shot changing at the end,0.390
85,Toon Blast-360 X 640-2026-01-22-7a6287a71ffebd...,6.12,0.0768,0.1054,0.0052,0,0,Metal nuts/bolts pour into a glass jar in one ...,"small metal balls falling into a glass jar, on...",0.390
32,Block Blast (1).mp4,6.20,0.1504,0.2792,0.0686,0,0,Static aerial view of a busy city street (Time...,guy comparing his hand size,0.430

In [ ]:
df.nlargest(10, "mean_frame_diff")[
    [
        "file_name",
        "duration_s",
        "mean_frame_diff",
        "max_frame_diff",
        "max_hist_diff",
        "scene_cuts",
        "manual_scene_cuts",
        "description",
        "personal description/observation"
    ]
]

,file_name,duration_s,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
32,Block Blast (1).mp4,6.20,0.1504,0.2792,0.0686,0,0,Static aerial view of a busy city street (Time...,guy comparing his hand size
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,0.1431,0.1782,0.3680,0,0,Skydiver free-falls through clouds and opens a...,correct
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.1303,0.2624,0.6913,1,4,"Race cars speed around a track, then the view ...",total 4 cuts observed
36,Block Blast.mp4,4.20,0.1174,0.2021,0.3442,1,1,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.1126,0.2224,0.6598,1,3,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
9,1e8c1cb1-eff0-45b0-b923-d6651209e08f_0.mp4,4.03,0.1047,0.1310,0.1905,0,0,Girl drives a red tractor; camera pulls back t...,correct

In [ ]:
df.nsmallest(10, "mean_frame_diff")[
    [
        "file_name",
        "duration_s",
        "mean_frame_diff",
        "max_frame_diff",
        "max_hist_diff",
        "scene_cuts",
        "manual_scene_cuts",
        "description",
        "personal description/observation"
    ]
]

,file_name,duration_s,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
2,108ec12b-6e43-41b6-a94b-86234f17b4f7_0.mp4,11.00,0.0036,0.0090,0.0001,0,0,Static senior-fitness survey ad card; checkbox...,correct
26,b118e186-fad6-42c9-b69f-7759a14c3b67_0.mp4,11.20,0.0037,0.0124,0.0024,0,0,Static senior-fitness survey ad card; checkbox...,correct
66,Solitaire - Card Games Classic-720 X 1280-2026...,3.92,0.0050,0.0264,0.0010,0,0,Static Solitaire app update screen with cards ...,correct
22,81dca706-0e11-4d4d-8f00-deee6a3decc7_0.mp4,12.52,0.0053,0.0484,0.3211,0,0,Static word-game ad card over rolling hills; c...,correct
95,Vita Solitaire for Seniors-360 X 640-2026-07-0...,12.30,0.0060,0.0573,0.5448,0,0,Static satellite/space station illustration wi...,correct
1,091e9575-40d4-4192-b0f0-9f63efbda572_0.mp4,3.92,0.0067,0.0167,0.0233,0,0,Static match-3 puzzle ad screen with fruit til...,nothing written on first card
16,3D Bolt Master®_ Screw Master®-480 X 480-2026-...,5.60,0.0074,0.0327,0.0095,0,0,Static cartoon-dog ad character at a table; ov...,Miniature figures trying to move a big boulder...
21,76c7b054-9c26-41e8-803f-673e700a36d2.mp4,3.50,0.0091,0.0100,0.0042,0,0,Static hillside/cloud landscape ad with a whit...,correct
60,LUDO_-360 X 640-2026-05-25-b2f788c4c4bfdb6eb2d...,3.92,0.0091,0.0151,0.0062,0,0,Woman's neutral face fills the frame with over...,correct
25,Amaze GO!-360 X 640-2026-06-18-5c06e9ed9f235f2...,5.70,0.0107,0.0286,0.0107,0,0,Woman sits by a window holding a letter; subti...,correct

Chose Candidates
##Candidate A

###mean_frame_diff + max_frame_diff + max_hist_diff

##Candidate B

###mean_frame_diff + max_hist_diff + scene_cuts

In [ ]:
model_features = [
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "scene_cuts"
]

for col in model_features:
    df[col + "_pct"] = df[col].rank(pct=True)

In [ ]:
df["score_A"] = (
    df["mean_frame_diff_pct"]
    + df["max_frame_diff_pct"]
    + df["max_hist_diff_pct"]
) / 3

df["score_B"] = (
    df["mean_frame_diff_pct"]
    + df["max_hist_diff_pct"]
    + df["scene_cuts_pct"]
) / 3

In [ ]:
df[[
    "file_name",
    "duration_s",
    "score_A",
    "score_B",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "scene_cuts",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]].sort_values("score_A", ascending=False).head(15)

,file_name,duration_s,score_A,score_B,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,0.960000,0.956667,0.1022,0.3607,1.3889,3,5,"Montage: a burning castle city, a dark cloud t...",correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,0.930000,0.911667,0.0807,0.4958,1.1788,2,2,"A boat capsizes in ocean waves, then cuts to a...",correct
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.910000,0.881667,0.1303,0.2624,0.6913,1,4,"Race cars speed around a track, then the view ...",total 4 cuts observed
77,teenpatti29.mp4,2.94,0.900000,0.875000,0.0853,0.2576,1.0292,1,2,Man talks to camera with a 'WINNER' banner ove...,2 cuts
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.895000,0.905000,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.895000,0.905000,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
73,Solitaire Smash_ Real Cash!-720 X 1280-2026-06...,3.80,0.873333,0.676667,0.0764,0.2908,0.7145,0,2,Man on a couch and a pregnant woman talk about...,"2 cuts, 3 frames"
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.865000,0.908333,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.865000,0.908333,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.856667,0.861667,0.1126,0.2224,0.6598,1,3,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,0.850000,0.851667,0.0604,0.2729,1.2282,2,2,"A mountain rock spelling 'ADS' crumbles, then ...",correct
32,Block Blast (1).mp4,6.20,0.823333,0.633333,0.1504,0.2792,0.0686,0,0,Static aerial view of a busy city street (Time...,guy comparing his hand size
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,0.810000,0.761667,0.0642,0.3086,0.5497,1,3,"Man and woman talk on a street, with a phone c...",total 3 cuts observed
74,Solitaire Smash_ Real Cash-720 X 1280-2026-06-...,5.00,0.806667,0.791667,0.0637,0.2336,0.7540,1,4,"Couple converse in a living room ('hey honey, ...",4 cuts
36,Block Blast.mp4,4.20,0.803333,0.818333,0.1174,0.2021,0.3442,1,1,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."

In [ ]:
df[[
    "file_name",
    "duration_s",
    "score_A",
    "score_B",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "scene_cuts",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]].sort_values("score_B", ascending=False).head(15)

,file_name,duration_s,score_A,score_B,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
46,Empires & Puzzles_ Match-3 RPG-720 X 1280-2026...,7.01,0.960000,0.956667,0.1022,0.3607,1.3889,3,5,"Montage: a burning castle city, a dark cloud t...",correct
39,Candy Crush Saga-360 X 640-2026-06-09-cdf0f762...,10.83,0.930000,0.911667,0.0807,0.4958,1.1788,2,2,"A boat capsizes in ocean waves, then cuts to a...",correct
64,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.865000,0.908333,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
65,Royal Match-720 X 1280-2026-07-08-8d0282690e2a...,8.60,0.865000,0.908333,0.1138,0.2295,0.5787,4,0,TikTok-style ad rapidly cuts between a woman h...,no scene cut
58,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.895000,0.905000,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
57,Ludo STAR-720 X 720-2026-06-25-7cbd0d2c48eca66...,4.40,0.895000,0.905000,0.1421,0.2217,0.8413,1,0,"Colored marbles race down a glowing track, the...",text appear on the same shot not cut to a diff...
54,Ludo STAR-360 X 640-2026-04-27-c9e337f0c6acd1c...,4.90,0.910000,0.881667,0.1303,0.2624,0.6913,1,4,"Race cars speed around a track, then the view ...",total 4 cuts observed
77,teenpatti29.mp4,2.94,0.900000,0.875000,0.0853,0.2576,1.0292,1,2,Man talks to camera with a 'WINNER' banner ove...,2 cuts
3,1774855008922425.mp4,3.80,0.736667,0.875000,0.0725,0.1090,0.9726,2,2,"Wooden box unfolds into a flat Ludo board, whi...",correct
75,Tasty Travels_ Merge Game-1080 X 1920-2026-07-...,8.30,0.856667,0.861667,0.1126,0.2224,0.6598,1,3,Bottles labeled 'no ads/no wifi' on a balcony ...,3 cuts observed
94,Vita Solitaire for Seniors-1080 X 1920-2026-07...,11.00,0.850000,0.851667,0.0604,0.2729,1.2282,2,2,"A mountain rock spelling 'ADS' crumbles, then ...",correct
36,Block Blast.mp4,4.20,0.803333,0.818333,0.1174,0.2021,0.3442,1,1,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."
53,Ludo King-512 X 640-2026-06-04-e0e58800a975d18...,7.50,0.790000,0.811667,0.0980,0.1933,0.4085,1,0,Fiery corridor and smoke effects coalesce into...,corect
74,Solitaire Smash_ Real Cash-720 X 1280-2026-06-...,5.00,0.806667,0.791667,0.0637,0.2336,0.7540,1,4,"Couple converse in a living room ('hey honey, ...",4 cuts
59,Ludo SuperStar-360 X 360-2026-06-10-81624a2cc8...,4.00,0.733333,0.785000,0.0612,0.1638,0.8137,1,1,Dice roll on a Ludo board with pieces; camera ...,rotating ludo board then scene cuts to a dice ...

In [ ]:
# How strongly does each candidate score relate to manually observed scene changes?

df[[
    "score_A",
    "score_B",
    "manual_scene_cuts"
]].corr().round(2)

                   score_A  score_B  manual_scene_cuts
score_A               1.00     0.96               0.50
score_B               0.96     1.00               0.52
manual_scene_cuts     0.50     0.52               1.00

In [ ]:
# Average candidate scores by number of manually observed scene cuts

df.groupby("manual_scene_cuts")[["score_A", "score_B"]].agg(
    ["count", "mean", "median"]
).round(3)

                  score_A               score_B
                    count   mean median   count   mean median
manual_scene_cuts
0                      69  0.428  0.390      69  0.437  0.397
1                      12  0.551  0.585      12  0.539  0.503
2                      13  0.715  0.717      13  0.698  0.682
3                       2  0.833  0.833       2  0.812  0.812
4                       3  0.814  0.807       3  0.743  0.792
5                       1  0.960  0.960       1  0.957  0.957

In [ ]:
five_to_seven = df[
    (df["duration_s"] > 5) &
    (df["duration_s"] <= 7)
].copy()

five_to_seven[
    [
        "file_name",
        "duration_s",
        "score_A",
        "score_B",
        "mean_frame_diff",
        "max_frame_diff",
        "max_hist_diff",
        "scene_cuts",
        "manual_scene_cuts",
        "description",
        "personal description/observation"
    ]
].sort_values("score_A", ascending=False)

,file_name,duration_s,score_A,score_B,mean_frame_diff,max_frame_diff,max_hist_diff,scene_cuts,manual_scene_cuts,description,personal description/observation
32,Block Blast (1).mp4,6.20,0.823333,0.633333,0.1504,0.2792,0.0686,0,0,Static aerial view of a busy city street (Time...,guy comparing his hand size
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,0.810000,0.761667,0.0642,0.3086,0.5497,1,3,"Man and woman talk on a street, with a phone c...",total 3 cuts observed
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,0.796667,0.686667,0.1431,0.1782,0.3680,0,0,Skydiver free-falls through clouds and opens a...,correct
51,jYn03l7-G46sBmDOIWUDA_output.mp4,5.04,0.750000,0.745000,0.0544,0.2891,0.4226,2,2,Interview cuts between a woman and a man talki...,correct
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,6.32,0.726667,0.556667,0.0627,0.2373,0.2798,0,4,"Two men fish by a river; one runs off, then a ...","4 cuts, wrong observation by LLM"
4,1774855609672222 (1).mp4,6.27,0.685000,0.681667,0.0207,0.2291,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
5,1774855609672222.mp4,6.27,0.685000,0.681667,0.0207,0.2291,1.2000,1,2,Boy watches an old TV that switches from carto...,correct
47,Gardenscapes-720 X 1280-2026-06-29-784808c0fc1...,6.00,0.580000,0.611667,0.0391,0.1869,0.1706,1,2,"Bride holds a bouquet in a dressing room, then...","a girl handing over bouquet to bride, cuts onl..."
79,Texas Hold_em Poker_ Pokerist-1280 X 720-2026-...,6.30,0.573333,0.510000,0.0532,0.1294,0.1971,0,0,Camera moves through a spooky night graveyard/...,correct
85,Toon Blast-360 X 640-2026-01-22-7a6287a71ffebd...,6.12,0.476667,0.433333,0.0768,0.1054,0.0052,0,0,Metal nuts/bolts pour into a glass jar in one ...,"small metal balls falling into a glass jar, on..."
17,43f383c4-eb58-4291-8498-0bc7b0d8ce23_0.mp4,5.12,0.436667,0.358333,0.0347,0.1333,0.0138,0,0,A hydraulic press descends and crushes a yello...,camera rotation at the very end
38,c0ade7f5-1bff-4ae9-90a4-647bef4d60b7_0.mp4,6.20,0.373333,0.363333,0.0323,0.0792,0.0238,0,0,A knife heats in glowing coals until it ignite...,"knife cutting a a lavaa dragon skull, one shot"
24,a40e3cn3zxrmy0cx02sr4348h0_result_.mp4,6.50,0.356667,0.336667,0.0399,0.0842,0.0086,0,0,"A hand slices a cheeseburger with a knife, one...",correct
89,Township-720 X 1280-2026-06-04-376e380efe460ba...,6.70,0.313333,0.340000,0.0330,0.0585,0.0131,0,0,Aerial view of a farm where a chicken flock re...,correct
27,bc3e1e2d-c49a-4377-bcf9-dde9a9029cd7_0.mp4,5.20,0.230000,0.230000,0.0144,0.0751,0.0071,0,0,Static 'Play Ludo with 4 Players' app store ad...,correct
88,Township-6.mp4,6.20,0.186667,0.250000,0.0127,0.0410,0.0118,0,0,Woman carries a giant egg past chickens on a f...,correct
81,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,5.20,0.155000,0.253333,0.0164,0.0284,0.0088,0,0,An elderly man and a robot solve a dot-connect...,correct
16,3D Bolt Master®_ Screw Master®-480 X 480-2026-...,5.60,0.145000,0.223333,0.0074,0.0327,0.0095,0,0,Static cartoon-dog ad character at a table; ov...,Miniature figures trying to move a big boulder...
25,Amaze GO!-360 X 640-2026-06-18-5c06e9ed9f235f2...,5.70,0.143333,0.236667,0.0107,0.0286,0.0107,0,0,Woman sits by a window holding a letter; subti...,correct

Risk Score

In [ ]:
for col in [
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff"
]:
    df[col + "_pct"] = df[col].rank(pct=True)

In [ ]:
df["risk_score"] = 100 * (
    0.40 * df["mean_frame_diff_pct"] +
    0.30 * df["max_frame_diff_pct"] +
    0.30 * df["max_hist_diff_pct"]
)

In [ ]:
df[(df["duration_s"] > 5) & (df["duration_s"] <= 7)]

,file_name,decision,duration_s,width,height,fps,mean_frame_diff,max_frame_diff,p90_frame_diff,std_frame_diff,...,description,personal description/observation,max_frame_minus_hist,mean_frame_diff_pct,max_frame_diff_pct,max_hist_diff_pct,scene_cuts_pct,score_A,score_B,risk_score
4,1774855609672222 (1).mp4,ELIGIBLE,6.27,720,1280,30.0,0.0207,0.2291,0.0200,0.0351,...,Boy watches an old TV that switches from carto...,correct,-0.130,0.235,0.845,0.975,0.835,0.685000,0.681667,64.00
5,1774855609672222.mp4,ELIGIBLE,6.27,720,1280,30.0,0.0207,0.2291,0.0200,0.0351,...,Boy watches an old TV that switches from carto...,correct,-0.130,0.235,0.845,0.975,0.835,0.685000,0.681667,64.00
16,3D Bolt Master®_ Screw Master®-480 X 480-2026-...,ELIGIBLE,5.60,480,480,30.0,0.0074,0.0327,0.0137,0.0063,...,Static cartoon-dog ad character at a table; ov...,Miniature figures trying to move a big boulder...,-0.075,0.070,0.145,0.220,0.380,0.145000,0.223333,13.75
17,43f383c4-eb58-4291-8498-0bc7b0d8ce23_0.mp4,ELIGIBLE,5.12,360,640,24.0,0.0347,0.1333,0.0366,0.0187,...,A hydraulic press descends and crushes a yello...,camera rotation at the very end,0.315,0.395,0.615,0.300,0.380,0.436667,0.358333,43.25
24,a40e3cn3zxrmy0cx02sr4348h0_result_.mp4,ELIGIBLE,6.50,720,1280,30.0,0.0399,0.0842,0.0703,0.0186,...,"A hand slices a cheeseburger with a knife, one...",correct,0.250,0.440,0.440,0.190,0.380,0.356667,0.336667,36.50
25,Amaze GO!-360 X 640-2026-06-18-5c06e9ed9f235f2...,ELIGIBLE,5.70,360,640,30.0,0.0107,0.0286,0.0205,0.0073,...,Woman sits by a window holding a letter; subti...,correct,-0.130,0.100,0.100,0.230,0.380,0.143333,0.236667,13.90
27,bc3e1e2d-c49a-4377-bcf9-dde9a9029cd7_0.mp4,ELIGIBLE,5.20,592,334,25.0,0.0144,0.0751,0.0240,0.0129,...,Static 'Play Ludo with 4 Players' app store ad...,correct,0.210,0.140,0.380,0.170,0.380,0.230000,0.230000,22.10
32,Block Blast (1).mp4,EXCLUDE,6.20,1080,1920,30.0,0.1504,0.2792,0.2369,0.0651,...,Static aerial view of a busy city street (Time...,guy comparing his hand size,0.430,1.000,0.950,0.520,0.380,0.823333,0.633333,84.10
38,c0ade7f5-1bff-4ae9-90a4-647bef4d60b7_0.mp4,ELIGIBLE,6.20,720,1280,30.0,0.0323,0.0792,0.0570,0.0153,...,A knife heats in glowing coals until it ignite...,"knife cutting a a lavaa dragon skull, one shot",0.050,0.350,0.410,0.360,0.380,0.373333,0.363333,37.10
47,Gardenscapes-720 X 1280-2026-06-29-784808c0fc1...,ELIGIBLE,6.00,720,1280,30.0,0.0391,0.1869,0.0803,0.0422,...,"Bride holds a bouquet in a dressing room, then...","a girl handing over bouquet to bride, cuts onl...",0.170,0.430,0.740,0.570,0.835,0.580000,0.611667,56.50
51,jYn03l7-G46sBmDOIWUDA_output.mp4,ELIGIBLE,5.04,716,1284,24.0,0.0544,0.2891,0.0857,0.0652,...,Interview cuts between a woman and a man talki...,correct,0.230,0.560,0.960,0.730,0.945,0.750000,0.745000,73.10
69,Solitaire Associations Journey-720 X 900-2026-...,ELIGIBLE,5.90,720,900,30.0,0.1431,0.1782,0.1671,0.0204,...,Skydiver free-falls through clouds and opens a...,correct,0.020,0.990,0.710,0.690,0.380,0.796667,0.686667,81.60
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,ELIGIBLE,5.40,224,398,15.0,0.0642,0.3086,0.1429,0.0710,...,"Man and woman talk on a street, with a phone c...",total 3 cuts observed,0.210,0.680,0.980,0.770,0.835,0.810000,0.761667,79.70
79,Texas Hold_em Poker_ Pokerist-1280 X 720-2026-...,ELIGIBLE,6.30,1280,720,30.0,0.0532,0.1294,0.0944,0.0294,...,Camera moves through a spooky night graveyard/...,correct,-0.030,0.550,0.570,0.600,0.380,0.573333,0.510000,57.10
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,ELIGIBLE,6.32,720,1280,25.0,0.0627,0.2373,0.1392,0.0568,...,"Two men fish by a river; one runs off, then a ...","4 cuts, wrong observation by LLM",0.250,0.650,0.890,0.640,0.380,0.726667,0.556667,71.90
81,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,ELIGIBLE,5.20,360,640,30.0,0.0164,0.0284,0.0237,0.0049,...,An elderly man and a robot solve a dot-connect...,correct,-0.115,0.180,0.085,0.200,0.380,0.155000,0.253333,15.75
85,Toon Blast-360 X 640-2026-01-22-7a6287a71ffebd...,ELIGIBLE,6.12,360,640,25.0,0.0768,0.1054,0.1000,0.0188,...,Metal nuts/bolts pour into a glass jar in one ...,"small metal balls falling into a glass jar, on...",0.390,0.800,0.510,0.120,0.380,0.476667,0.433333,50.90
88,Township-6.mp4,ELIGIBLE,6.20,360,640,30.0,0.0127,0.0410,0.0195,0.0067,...,Woman carries a giant egg past chickens on a f...,correct,-0.060,0.120,0.190,0.250,0.380,0.186667,0.250000,18.00
89,Township-720 X 1280-2026-06-04-376e380efe460ba...,ELIGIBLE,6.70,720,1280,30.0,0.0330,0.0585,0.0411,0.0088,...,Aerial view of a farm where a chicken flock re...,correct,0.020,0.360,0.300,0.280,0.380,0.313333,0.340000,31.80

In [ ]:
for col in [
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff"
]:
    df[col + "_pct"] = df[col].rank(pct=True)

In [ ]:
df["risk_score"] = 100 * (
    0.40 * df["mean_frame_diff_pct"] +
    0.30 * df["max_frame_diff_pct"] +
    0.30 * df["max_hist_diff_pct"]
)

In [ ]:
df[[
    "file_name",
    "duration_s",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "risk_score"
]].head()

,file_name,duration_s,mean_frame_diff,max_frame_diff,max_hist_diff,risk_score
0,086043fa-911b-4e4a-a3ec-81a80096e335_0.mp4,3.71,0.0176,0.0537,0.0035,17.7
1,091e9575-40d4-4192-b0f0-9f63efbda572_0.mp4,3.92,0.0067,0.0167,0.0233,14.4
2,108ec12b-6e43-41b6-a94b-86234f17b4f7_0.mp4,11.00,0.0036,0.0090,0.0001,1.3
3,1774855008922425.mp4,3.80,0.0725,0.1090,0.9726,73.8
4,1774855609672222 (1).mp4,6.27,0.0207,0.2291,1.2000,64.0

In [ ]:
# Overall risk-score distribution
df["risk_score"].describe()

count    100.00000
mean      50.50000
std       25.71692
min        1.30000
25%       27.70000
50%       52.27500
75%       72.15000
max       95.30000
Name: risk_score, dtype: float64

In [ ]:
five_to_seven = df[
    (df["duration_s"] > 5) &
    (df["duration_s"] <= 7)
].copy()

five_to_seven[
    [
        "file_name",
        "duration_s",
        "risk_score",
        "mean_frame_diff",
        "max_frame_diff",
        "max_hist_diff",
        "manual_scene_cuts",
        "description"
    ]
].sort_values("risk_score")

,file_name,duration_s,risk_score,mean_frame_diff,max_frame_diff,max_hist_diff,manual_scene_cuts,description
16,3D Bolt Master®_ Screw Master®-480 X 480-2026-...,5.60,13.75,0.0074,0.0327,0.0095,0,Static cartoon-dog ad character at a table; ov...
25,Amaze GO!-360 X 640-2026-06-18-5c06e9ed9f235f2...,5.70,13.90,0.0107,0.0286,0.0107,0,Woman sits by a window holding a letter; subti...
81,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,5.20,15.75,0.0164,0.0284,0.0088,0,An elderly man and a robot solve a dot-connect...
88,Township-6.mp4,6.20,18.00,0.0127,0.0410,0.0118,0,Woman carries a giant egg past chickens on a f...
27,bc3e1e2d-c49a-4377-bcf9-dde9a9029cd7_0.mp4,5.20,22.10,0.0144,0.0751,0.0071,0,Static 'Play Ludo with 4 Players' app store ad...
89,Township-720 X 1280-2026-06-04-376e380efe460ba...,6.70,31.80,0.0330,0.0585,0.0131,0,Aerial view of a farm where a chicken flock re...
24,a40e3cn3zxrmy0cx02sr4348h0_result_.mp4,6.50,36.50,0.0399,0.0842,0.0086,0,"A hand slices a cheeseburger with a knife, one..."
38,c0ade7f5-1bff-4ae9-90a4-647bef4d60b7_0.mp4,6.20,37.10,0.0323,0.0792,0.0238,0,A knife heats in glowing coals until it ignite...
17,43f383c4-eb58-4291-8498-0bc7b0d8ce23_0.mp4,5.12,43.25,0.0347,0.1333,0.0138,0,A hydraulic press descends and crushes a yello...
85,Toon Blast-360 X 640-2026-01-22-7a6287a71ffebd...,6.12,50.90,0.0768,0.1054,0.0052,0,Metal nuts/bolts pour into a glass jar in one ...
47,Gardenscapes-720 X 1280-2026-06-29-784808c0fc1...,6.00,56.50,0.0391,0.1869,0.1706,2,"Bride holds a bouquet in a dressing room, then..."
79,Texas Hold_em Poker_ Pokerist-1280 X 720-2026-...,6.30,57.10,0.0532,0.1294,0.1971,0,Camera moves through a spooky night graveyard/...
4,1774855609672222 (1).mp4,6.27,64.00,0.0207,0.2291,1.2000,2,Boy watches an old TV that switches from carto...
5,1774855609672222.mp4,6.27,64.00,0.0207,0.2291,1.2000,2,Boy watches an old TV that switches from carto...
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,6.32,71.90,0.0627,0.2373,0.2798,4,"Two men fish by a river; one runs off, then a ..."
51,jYn03l7-G46sBmDOIWUDA_output.mp4,5.04,73.10,0.0544,0.2891,0.4226,2,Interview cuts between a woman and a man talki...
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,79.70,0.0642,0.3086,0.5497,3,"Man and woman talk on a street, with a phone c..."
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,81.60,0.1431,0.1782,0.3680,0,Skydiver free-falls through clouds and opens a...
32,Block Blast (1).mp4,6.20,84.10,0.1504,0.2792,0.0686,0,Static aerial view of a busy city street (Time...

In [ ]:
thresholds = [50, 55, 60, 65, 70, 75, 80]

threshold_summary = []

for t in thresholds:
    eligible_all = (df["risk_score"] <= t).sum()
    eligible_5_7 = (five_to_seven["risk_score"] <= t).sum()

    threshold_summary.append({
        "threshold": t,
        "eligible_all_100": eligible_all,
        "excluded_all_100": len(df) - eligible_all,
        "eligible_5_7": eligible_5_7,
        "excluded_5_7": len(five_to_seven) - eligible_5_7
    })

pd.DataFrame(threshold_summary)

   threshold  eligible_all_100  excluded_all_100  eligible_5_7  excluded_5_7
0         50                46                54             9            10
1         55                52                48            10             9
2         60                59                41            12             7
3         65                68                32            14             5
4         70                72                28            14             5
5         75                79                21            16             3
6         80                86                14            17             2

In [ ]:
THRESHOLD = 65

df["model_decision"] = df["risk_score"].apply(
    lambda x: "ELIGIBLE" if x <= THRESHOLD else "EXCLUDE"
)

df["model_decision"].value_counts()

model_decision
ELIGIBLE    68
EXCLUDE     32
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    df["decision"],
    df["model_decision"],
    margins=True
)

model_decision  ELIGIBLE  EXCLUDE  All
decision
ELIGIBLE              54       18   72
EXCLUDE               14       14   28
All                   68       32  100

In [ ]:
df[
    (df["decision"] == "EXCLUDE") &
    (df["model_decision"] == "ELIGIBLE")
][[
    "file_name",
    "duration_s",
    "risk_score",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]].sort_values("risk_score")

,file_name,duration_s,risk_score,mean_frame_diff,max_frame_diff,max_hist_diff,manual_scene_cuts,description,personal description/observation
2,108ec12b-6e43-41b6-a94b-86234f17b4f7_0.mp4,11.00,1.30,0.0036,0.0090,0.0001,0,Static senior-fitness survey ad card; checkbox...,correct
26,b118e186-fad6-42c9-b69f-7759a14c3b67_0.mp4,11.20,3.50,0.0037,0.0124,0.0024,0,Static senior-fitness survey ad card; checkbox...,correct
62,Royal Match-360 X 640-2026-07-08-3e21d832a67a3...,7.62,9.65,0.0121,0.0327,0.0002,0,Line-drawing animation of a small figure inter...,correct
91,Township-720 X 720-2026-07-03-293ca71cc156f3c4...,10.60,24.50,0.0162,0.0304,0.0386,0,Farm woman walks past a barn and sheep while d...,fram woman trying to push haystack into the barn
22,81dca706-0e11-4d4d-8f00-deee6a3decc7_0.mp4,12.52,27.70,0.0053,0.0484,0.3211,0,Static word-game ad card over rolling hills; c...,correct
52,Last War_Survival-360 X 360-2026-07-15-1f33786...,10.72,31.50,0.0282,0.0558,0.0200,0,Two men sit at a table talking; on-screen scor...,correct
33,Block Blast (2).mp4,7.10,32.70,0.0269,0.0865,0.0094,2,A pencil draws lines connecting matching color...,"correct, excluded possibly due to inconsistent..."
95,Vita Solitaire for Seniors-360 X 640-2026-07-0...,12.30,33.50,0.0060,0.0573,0.5448,0,Static satellite/space station illustration wi...,correct
82,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,11.80,34.90,0.0154,0.0323,0.6391,0,Static illustrated senior portrait with a moun...,correct
83,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,11.80,38.50,0.0490,0.0766,0.0110,0,Static jungle waterfall photo background with ...,correct
11,30bb4e52-61f1-45c8-ad90-895bfb0b6a70_0.mp4,9.03,59.40,0.0759,0.1009,0.0343,0,Cookie-dough characters jump into a deep fryer...,single fry character flipping into deep fryer
92,Untitled design (19).mp4,9.60,60.70,0.0408,0.1566,0.5227,1,Two food-mascot characters argue in a fridge/k...,one cut between
6,1774909312798671.mp4,3.70,61.90,0.0699,0.1031,0.1951,2,Angry green troll character shoots fire in a b...,"Detected anomalies in the frame, initally char..."
84,Tile Explorer_ Tiles Clear!-360 X 640-2026-06-...,8.80,64.50,0.0527,0.1822,0.4041,0,Close underwater texture shot transitions to a...,"no cuts, one continuous shot camera moving up ..."

In [ ]:
df[
    (df["decision"] == "ELIGIBLE") &
    (df["model_decision"] == "EXCLUDE")
][[
    "file_name",
    "duration_s",
    "risk_score",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "manual_scene_cuts",
    "description",
    "personal description/observation"
]].sort_values("risk_score")

,file_name,duration_s,risk_score,mean_frame_diff,max_frame_diff,max_hist_diff,manual_scene_cuts,description,personal description/observation
90,Township-720 X 1280-2026-07-03-c32a10836b1a3b4...,3.70,66.70,0.0804,0.1840,0.0276,0,Farm woman stands with a cow as a stack of mil...,correct
7,1774909640157727.mp4,3.10,69.10,0.0859,0.1387,0.0710,0,Wooden hand/ladder figure reaches up a mountai...,King like character climbing up a hand like la...
9,1e8c1cb1-eff0-45b0-b923-d6651209e08f_0.mp4,4.03,71.50,0.1047,0.1310,0.1905,0,Girl drives a red tractor; camera pulls back t...,correct
80,Tile Explorer - Triple Match-720 X 1280-2026-0...,6.32,71.90,0.0627,0.2373,0.2798,4,"Two men fish by a river; one runs off, then a ...","4 cuts, wrong observation by LLM"
35,Block Blast-360 X 640-2026-07.mp4,4.10,72.10,0.0751,0.1704,0.4031,0,Hands play a Chinese-checkers-style marble boa...,correct
59,Ludo SuperStar-360 X 360-2026-06-10-81624a2cc8...,4.00,72.30,0.0612,0.1638,0.8137,1,Dice roll on a Ludo board with pieces; camera ...,rotating ludo board then scene cuts to a dice ...
41,Coloring Games-1080 X 1920-2026-07-15-7af7eaa0...,3.00,72.40,0.0619,0.2694,0.2794,1,Camera zooms in on a candy-stamping machine in...,one cut in between two shots
51,jYn03l7-G46sBmDOIWUDA_output.mp4,5.04,73.10,0.0544,0.2891,0.4226,2,Interview cuts between a woman and a man talki...,correct
3,1774855008922425.mp4,3.80,73.80,0.0725,0.1090,0.9726,2,"Wooden box unfolds into a flat Ludo board, whi...",correct
98,Word Search Zen-Word Find-720 X 1280-2026-01-2...,3.30,75.20,0.0892,0.1722,0.3235,0,A hand presses a blue slime case with rubber d...,correct
76,Tasty Travels_ Merge Game-360 X 640-2026-07-07...,3.60,77.40,0.1028,0.2228,0.1130,0,Girl rides a toy lawn mower blowing flower pet...,she isn't riding but only blowing there are no...
12,32c5b45f-abd3-4efc-9824-7f713b5f8c4e_0.mp4,5.00,77.80,0.0589,0.2557,0.7799,0,"Boy lies in bed lit by phone glow, texting; on...",Lady using phone lying on bed under cover
97,Word Search Zen-Word Find-720 X 1280-2026-01-2...,3.70,78.45,0.0661,0.1917,0.9971,0,A styrofoam block is carved/crushed in one con...,correct
71,Solitaire Smash_ Real Cash!-224 X 400-2026-06-...,5.40,79.70,0.0642,0.3086,0.5497,3,"Man and woman talk on a street, with a phone c...",total 3 cuts observed
69,Solitaire Associations Journey-720 X 900-2026-...,5.90,81.60,0.1431,0.1782,0.3680,0,Skydiver free-falls through clouds and opens a...,correct
36,Block Blast.mp4,4.20,81.80,0.1174,0.2021,0.3442,1,"Two cats hug inside a cage in a dark alley, th...","one cut, frame changed to a kitten dancing on ..."
73,Solitaire Smash_ Real Cash!-720 X 1280-2026-06...,3.80,86.50,0.0764,0.2908,0.7145,2,Man on a couch and a pregnant woman talk about...,"2 cuts, 3 frames"
77,teenpatti29.mp4,2.94,89.40,0.0853,0.2576,1.0292,2,Man talks to camera with a 'WINNER' banner ove...,2 cuts

In [ ]:
THRESHOLD = 65

df["model_decision"] = df.apply(
    lambda row: (
        "ELIGIBLE"
        if (row["duration_s"] <= 7) and (row["risk_score"] <= THRESHOLD)
        else "EXCLUDE"
    ),
    axis=1
)

In [ ]:
df["model_decision"].value_counts()

model_decision
ELIGIBLE    55
EXCLUDE     45
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    df["decision"],
    df["model_decision"],
    margins=True
)

model_decision  ELIGIBLE  EXCLUDE  All
decision
ELIGIBLE              54       18   72
EXCLUDE                1       27   28
All                   55       45  100

In [ ]:
expanded = df[
    (df["duration_s"] > 5) &
    (df["duration_s"] <= 7) &
    (df["model_decision"] == "ELIGIBLE")
]

len(expanded)

14

In [ ]:
weights = {
    "mean": 0.40,
    "max_frame": 0.30,
    "max_hist": 0.30
}

def make_decision(risk):
    return (
        (df["duration_s"] <= 7) &
        (risk <= THRESHOLD)
    )

base_risk = 100 * (
    weights["mean"] * df["mean_frame_diff_pct"] +
    weights["max_frame"] * df["max_frame_diff_pct"] +
    weights["max_hist"] * df["max_hist_diff_pct"]
)

base_decision = make_decision(base_risk)

sensitivity_results = []

for name, value in weights.items():
    for direction, multiplier in [("-20%", 0.8), ("+20%", 1.2)]:

        modified = weights.copy()
        modified[name] = value * multiplier

        modified_risk = 100 * (
            modified["mean"] * df["mean_frame_diff_pct"] +
            modified["max_frame"] * df["max_frame_diff_pct"] +
            modified["max_hist"] * df["max_hist_diff_pct"]
        )

        modified_decision = make_decision(modified_risk)

        flips = (modified_decision != base_decision).sum()

        sensitivity_results.append({
            "constant": name,
            "direction": direction,
            "base_value": value,
            "modified_value": modified[name],
            "decision_flips": flips
        })

sensitivity_df = pd.DataFrame(sensitivity_results)

sensitivity_df

    constant direction  base_value  modified_value  decision_flips
0       mean      -20%         0.4            0.32               3
1       mean      +20%         0.4            0.48               8
2  max_frame      -20%         0.3            0.24               1
3  max_frame      +20%         0.3            0.36               4
4   max_hist      -20%         0.3            0.24               1
5   max_hist      +20%         0.3            0.36               5

In [ ]:
def normalized_risk(w_mean, w_max_frame, w_max_hist):
    total = w_mean + w_max_frame + w_max_hist

    w_mean /= total
    w_max_frame /= total
    w_max_hist /= total

    return 100 * (
        w_mean * df["mean_frame_diff_pct"] +
        w_max_frame * df["max_frame_diff_pct"] +
        w_max_hist * df["max_hist_diff_pct"]
    )


sensitivity_results_norm = []

for name, value in weights.items():
    for direction, multiplier in [("-20%", 0.8), ("+20%", 1.2)]:

        modified = weights.copy()
        modified[name] = value * multiplier

        modified_risk = normalized_risk(
            modified["mean"],
            modified["max_frame"],
            modified["max_hist"]
        )

        modified_decision = (
            (df["duration_s"] <= 7) &
            (modified_risk <= THRESHOLD)
        )

        flips = (modified_decision != base_decision).sum()

        sensitivity_results_norm.append({
            "constant": name,
            "direction": direction,
            "base_value": value,
            "modified_value": modified[name],
            "decision_flips": flips
        })

pd.DataFrame(sensitivity_results_norm)

    constant direction  base_value  modified_value  decision_flips
0       mean      -20%         0.4            0.32               3
1       mean      +20%         0.4            0.48               0
2  max_frame      -20%         0.3            0.24               0
3  max_frame      +20%         0.3            0.36               3
4   max_hist      -20%         0.3            0.24               0
5   max_hist      +20%         0.3            0.36               2

In [ ]:
row37 = df.iloc[36]

print(row37[[
    "file_name",
    "duration_s",
    "mean_frame_diff",
    "max_frame_diff",
    "max_hist_diff",
    "mean_frame_diff_pct",
    "max_frame_diff_pct",
    "max_hist_diff_pct",
    "risk_score",
    "model_decision"
]])

print("\nArithmetic:")

q1 = row37["mean_frame_diff_pct"]
q2 = row37["max_frame_diff_pct"]
q3 = row37["max_hist_diff_pct"]

print(f"0.40 × {q1:.2f} = {0.40*q1:.3f}")
print(f"0.30 × {q2:.2f} = {0.30*q2:.3f}")
print(f"0.30 × {q3:.2f} = {0.30*q3:.3f}")
print(f"Risk score = {row37['risk_score']:.1f}")

file_name              Block Blast.mp4
duration_s                         4.2
mean_frame_diff                 0.1174
max_frame_diff                  0.2021
max_hist_diff                   0.3442
mean_frame_diff_pct               0.95
max_frame_diff_pct                0.79
max_hist_diff_pct                 0.67
risk_score                        81.8
model_decision                 EXCLUDE
Name: 36, dtype: object

Arithmetic:
0.40 × 0.95 = 0.380
0.30 × 0.79 = 0.237
0.30 × 0.67 = 0.201
Risk score = 81.8

In [ ]:
with pd.ExcelWriter("final_eligibility_analysis.xlsx", engine="openpyxl") as writer:

    final_columns = [
        "file_name",
        "duration_s",
        "width",
        "height",
        "fps",
        "mean_frame_diff",
        "max_frame_diff",
        "max_hist_diff",
        "mean_frame_diff_pct",
        "max_frame_diff_pct",
        "max_hist_diff_pct",
        "risk_score",
        "model_decision"
    ]

    calibration_columns = [
        "file_name",
        "scene_cuts",
        "manual_scene_cuts",
        "cuts_match",
        "description",
        "personal description/observation"
    ]

    df[final_columns].to_excel(
        writer,
        sheet_name="Final Decisions",
        index=False
    )

    df[calibration_columns].to_excel(
        writer,
        sheet_name="Calibration",
        index=False
    )

print("Saved final_eligibility_analysis.xlsx")

Saved final_eligibility_analysis.xlsx

In [ ]:
from google.colab import files
files.download("final_eligibility_analysis.xlsx")